INSERT INTO PUBLISHER VALUES('MCGRAW-HILL', 9980879786, 'BENGALURU');
INSERT INTO PUBLISHER VALUES('PEARSON', 9910873786, 'UDUPI');
INSERT INTO PUBLISHER VALUES('RADOM HOUSE', 998555486, 'USA');
INSERT INTO PUBLISHER VALUES('GRUPO PLANETA', 9980433786, 'UK');
INSERT INTO PUBLISHER VALUES('HILL SIDE PAPER', 9983379786, 'MYSORE');


INSERT INTO BOOK VALUES(1, 'DBMS', 'JAN-2017', 'MCGRAW-HILL');
INSERT INTO BOOK VALUES(2, 'AIML', 'JUN-2016', 'MCGRAW-HILL');
INSERT INTO BOOK VALUES(3, 'ATCD', 'SEP-2016', 'PEARSON');
INSERT INTO BOOK VALUES(4, 'OS', 'SEP-2015', 'GRUPO PLANETA');
INSERT INTO BOOK VALUES(5, 'CN', 'MAY-2016', 'PEARSON');

INSERT INTO BOOK_AUTHORS VALUES('NAVATHE', 1);
INSERT INTO BOOK_AUTHORS VALUES('NAVATHE', 2);
INSERT INTO BOOK_AUTHORS VALUES('TANENBAUM', 3);
INSERT INTO BOOK_AUTHORS VALUES('EDWARD ANGEL', 4);
INSERT INTO BOOK_AUTHORS VALUES('GALVIN', 5);

INSERT INTO LIBRARY_BRANCH VALUES(1, 'RR NAGAR', 'BENGALURU');
INSERT INTO LIBRARY_BRANCH VALUES(2, 'HOSKOTE', 'BENGALURU');
INSERT INTO LIBRARY_BRANCH VALUES(3, 'PUTTUR', 'MANGALURU');
INSERT INTO LIBRARY_BRANCH VALUES(4, 'NITTE', 'MANGALURU');
INSERT INTO LIBRARY_BRANCH VALUES(5, 'KARWAR', 'UTTARAKANNADA');


INSERT INTO CARD VALUES(10);
INSERT INTO CARD VALUES(20);
INSERT INTO CARD VALUES(30);
INSERT INTO CARD VALUES(40);
INSERT INTO CARD VALUES(50);

INSERT INTO BOOK_COPIES VALUES(10, 1, 1);
INSERT INTO BOOK_COPIES VALUES(15, 2, 3);
INSERT INTO BOOK_COPIES VALUES(13, 2, 2);
INSERT INTO BOOK_COPIES VALUES(14, 4, 2);
INSERT INTO BOOK_COPIES VALUES(15, 5, 1);


INSERT INTO BOOK_LENDING VALUES('01-JAN-17', '01-JUN-17', 1, 1, 10);
INSERT INTO BOOK_LENDING VALUES('11-JAN-17', '11-MAR-17', 3, 1, 20);
INSERT INTO BOOK_LENDING VALUES('21-FEB-17', '21-APR-17', 4, 2, 30);
INSERT INTO BOOK_LENDING VALUES('15-MAR-17', '15-JUN-17', 1, 2, 30);
INSERT INTO BOOK_LENDING VALUES('12-APR-17', '12-MAY-17', 2, 3, 40);





